function sol = solve_case(airfoil, N, alpha, u_inf, opts)
   % runs the whole panel method for one case
   arguments
       airfoil
       N
       alpha
       u_inf
       opts.WakeLength = 0.9
       opts.ClosedTE = true
       opts.FixGauge = true
       opts.OffsetFactor = 1e-4  
       opts.MomentRef = 0.25
   end

   t0 = tic;

   [x, z] = panelgen(airfoil, N, alpha, ...
       'WakeLength', opts.WakeLength, 'ClosedTE', opts.ClosedTE);

   [mu, info] = panel_strengths(x, z, u_inf, alpha, N, 'FixGauge', opts.FixGauge);

   [srf, coef] = surface_pressure(mu, x, z, u_inf, alpha, N, ...
       'OffsetFactor', opts.OffsetFactor, 'MomentRef', opts.MomentRef);

   sol = struct( ...
       'airfoil', airfoil, ...
       'N',       N, ...
       'alpha',   alpha, ...
       'u_inf',   u_inf, ...
       'x',       x, ...
       'z',       z, ...
       'mu',      mu, ...
       'info',    info, ...
       'surf',    srf, ...
       'coef',    coef, ...
       'runtime', toc(t0));

   % rough sanity check
   sol.possibleStall = min(srf.Cp) < -8;
   if sol.possibleStall
       warning('solve_case:possibleStall', ...
           ['min Cp = %.2f at alpha = %.1f deg - suction is unrealistically ' ...
            'high, this is well past where a real (viscous) flow would have ' ...
            'separated. treat Cl here as not physically meaningful.'], ...
           min(srf.Cp), alpha);
   end
end
